<?php
    require_once('classes.php');
class Tags extends Database
{
    public function resultset(){
        $posts = parent::resultset(); // TODO: Change the autogenerated stub
        if (is_array($posts) && count($posts)) {
            foreach ($posts as &$post) {
                $tags = [];
                $sql = "SELECT t.name FROM post_tags bpt LEFT JOIN tags t ON bpt.tag_id = t.id WHERE posts_id = :postid";
                parent::query($sql);
                parent::bind(':postid', $post['id']);
                $blogTags = parent::resultset();
                foreach ($blogTags as $btag) {
                    array_push($tags, $btag['name']);
                }
                $post['tags'] = implode(', ' . $tags);
            }

            return $posts;
        }

        else {
            return [];
        }
    }

}

?>